# Generated by Django 2.2.4 on 2019-10-22 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcinside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcinside',
            name='like_users',
            field=models.ManyToManyField(related_name='like_dcinside', to=settings.AUTH_USER_MODEL),
        ),
    ]
